version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    groups:
      composer:
        patterns:
          - '*'
    assignees:
      - mumincacao
